package alicloudroscdkcas


// Properties for defining a `SslCertificate`.
//
// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-cas-sslcertificate
type SslCertificateProps struct {
	// Property certBrand: Certificate brand.
	//
	// Valid values: Rapid, Globalsign, vTrus, Wosign, Digicert, Digicert pro, Geotrust, CFCA.
	// **Note:** This parameter must be specified along with or without the CertType and DomainTyp parameters.
	CertBrand interface{} `field:"optional" json:"certBrand" yaml:"certBrand"`
	// Property certType: Certificate type.
	//
	// Valid values: DV, OV, EV.
	// **Note:** This parameter must be specified along with or without the DomainType and CertBrand parameters.
	CertType interface{} `field:"optional" json:"certType" yaml:"certType"`
	// Property companyName: The name of the certificate application company.
	//
	// **Note**: This parameter is only applicable when applying for OV certificates.
	// When applying for OV certificate, if you set the company name here, it means that the corresponding company information in the information management module is used; If you do not set this parameter, it indicates that the latest company information added is selected from the information management module.
	CompanyName interface{} `field:"optional" json:"companyName" yaml:"companyName"`
	// Property csr: The content of the certificate signing request (CSR) file that is manually generated by using OpenSSL or Keytool for the domain name.
	//
	// The key algorithm in
	// the CSR file must be Rivest-Shamir-Adleman (RSA) or elliptic-curve cryptography
	// (ECC), and the key length of the RSA algorithm must be greater than or equal to
	// 2,048 characters. For more information about how to create a CSR file, see
	// [Create a CSR file](). If you do not specify this parameter, Certificate
	// Management Service automatically creates a CSR file.
	// A CSR file contains the information about your server and company. When you apply
	// for a certificate, you must submit the CSR file to the CA. The CA signs the CSR
	// file by using the private key of the root certificate and generates a public key
	// file to issue your certificate.
	// > The \*\*CN\*\* field in CSR file specifies the domain name that is bound to the
	// certificate. You must include the field in the parameter value.
	Csr interface{} `field:"optional" json:"csr" yaml:"csr"`
	// Property domains: The domain to bind the certificate to.
	//
	// The specific requirements are as follows:
	// - Supports single or wildcard domains (e.g., *.aliyundoc.com).
	// - Multiple domains are supported. You can set up to 5 domains.
	// - If you set more than one domain name, the multiple domains can only be single domain name or wildcard domain name, not both single domain name and wildcard domain name.
	// **Note:** This is required when the certificate is bound to more than one hostname. This parameter is not allowed to be empty at the same time as the Csr parameter. If you set both this parameter and the Csr parameter, take the CN field value in the Csr as the domain name for the certificate to bind to.
	Domains interface{} `field:"optional" json:"domains" yaml:"domains"`
	// Property domainType: Domain type.
	//
	// Valid values: one, all, multiple.
	// **Note:** This parameter must be specified along with or without the CertType and CertBrand parameters.
	DomainType interface{} `field:"optional" json:"domainType" yaml:"domainType"`
	// Property email: The email address of the applicant.
	//
	// After the CA receives your certificate
	// application, the CA sends a verification email to the email address that you
	// specify. You must log on to the mailbox, open the mail, and complete the
	// verification of the domain name ownership based on the steps that are described
	// in the email.
	// If you do not specify this parameter, the information about the most recent
	// contact that is added to the Information Management module is used. For more
	// information about how to add a contact to the Information Management module, see
	// [Manage contacts]().
	Email interface{} `field:"optional" json:"email" yaml:"email"`
	// Property phone: The contact phone number of the applicant.
	//
	// CA staff can call the phone number to
	// confirm the information in your certificate application.
	// If you do not specify this parameter, the information about the most recent
	// contact that is added to the Information Management module is used. For more
	// information about how to add a contact to the Information Management module, see
	// [Manage contacts]().
	Phone interface{} `field:"optional" json:"phone" yaml:"phone"`
	// Property productCode: The specifications of the certificate that you want to apply for.
	//
	// Valid values:
	// - digicert-free-1-free (default): DigiCert single-domain domain validated (DV)
	// certificate, which is free and valid for 3 months.
	// - symantec-free-1-free: DigiCert single-domain DV certificate, which is free and
	// valid for 1 year.
	// - symantec-dv-1-starter: DigiCert wildcard DV certificate.
	// - symantec-ov-1-personal: DigiCert single-domain organization validated (OV)
	// certificate.
	// - symantec-ov-w-personal: DigiCert wildcard OV certificate.
	// - geotrust-dv-1-starter: GeoTrust single-domain DV certificate.
	// - geotrust-dv-w-starter: GeoTrust wildcard DV certificate.
	// - geotrust-ov-1-personal: GeoTrust single-domain OV certificate.
	// - geotrust-ov-w-personal: GeoTrust wildcard OV certificate.
	// - globalsign-dv-1-personal: GlobalSign single-domain DV certificate.
	// - globalsign-dv-w-advanced: GlobalSign wildcard DV certificate.
	// - globalsign-ov-1-personal: GlobalSign single-domain OV certificate.
	// - globalsign-ov-w-advanced: GlobalSign wildcard OV certificate.
	// - cfca-ov-1-personal: China Financial Certification Authority (CFCA)
	// single-domain OV certificate.
	// - cfca-ev-w-advanced: CFCA wildcard OV certificate.
	ProductCode interface{} `field:"optional" json:"productCode" yaml:"productCode"`
	// Property username: The name of the applicant.
	//
	// If you do not specify this parameter, the information about the most recent
	// contact that is added to the Information Management module is used. For more
	// information about how to add a contact to the Information Management module, see
	// [Manage contacts]().
	Username interface{} `field:"optional" json:"username" yaml:"username"`
	// Property validateType: How domain ownership is verified.
	//
	// Valid values:
	// - DNS: DNS validation The ownership of the domain name is verified by adding a TXT type DNS record to the domain name's DNS management platform. You need administrative permission for domain resolution to complete validation.
	// - FILE: File validation Ownership of a domain name is verified by creating a specified file on the domain name server. You need administrator access to your domain name server to complete validation.
	ValidateType interface{} `field:"optional" json:"validateType" yaml:"validateType"`
}

