package alicloudroscdkmemcache


// Properties for defining a `Whitelist`.
//
// See https://www.alibabacloud.com/help/ros/developer-reference/aliyun-memcache-whitelist
type WhitelistProps struct {
	// Property instanceId: Instance ID (globally unique).
	InstanceId interface{} `field:"required" json:"instanceId" yaml:"instanceId"`
	// Property securityIps: The IP addresses in the whitelist.
	//
	// Up to 1,000 IP addresses can be specified in a
	// whitelist. Separate multiple IP addresses with a comma (,). Specify an IP address
	// in the 0.0.0.0\/0, 10.23.12.24, or 10.23.12.24\/24 format. In CIDR block
	// 10.23.12.24\/24, \/24 specifies the length of the prefix of an IP address. The
	// prefix length ranges from 1 to 32.
	SecurityIps interface{} `field:"required" json:"securityIps" yaml:"securityIps"`
	// Property securityIpGroupAttribute: The default is empty.
	//
	// For distinguishing between different attribute values, the console will not display the value of hidden whitelist packet.
	SecurityIpGroupAttribute interface{} `field:"optional" json:"securityIpGroupAttribute" yaml:"securityIpGroupAttribute"`
	// Property securityIpGroupName: The name of the IP address whitelist.
	//
	// ><warning>You cannot modify the whitelist that is generated by the system. If you
	// do not specify this parameter, the default whitelist is modified by
	// default.><\/warning>
	SecurityIpGroupName interface{} `field:"optional" json:"securityIpGroupName" yaml:"securityIpGroupName"`
}

